# Generated by Django 6.0.7 on 2026-08-10 23:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MapSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('all_can_edit', models.BooleanField(default=True)),
                ('map_selected', models.IntegerField(choices=[(1, 'Arras'), (2, 'Kuban'), (3, 'Lapino'), (4, 'Moscow'), (5, 'Normandy'), (6, 'Novosokolniki'), (7, 'Odessa'), (8, 'Prokhorovka'), (9, 'Rheinland'), (10, 'Stalingrad'), (11, 'Vluki'), (12, 'Western Front')])),
                ('has_access', models.ManyToManyField(blank=True, related_name='accessible_sessions', to=settings.AUTH_USER_MODEL)),
                ('permitted_to_edit', models.ManyToManyField(blank=True, related_name='editable_sessions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'slug')},
            },
        ),
    ]
