# Generated by Django 6.0.7 on 2026-08-14 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapSessions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapsession',
            name='has_access',
        ),
        migrations.RemoveField(
            model_name='mapsession',
            name='is_visible',
        ),
    ]
