# Generated by Django 6.0.7 on 2026-08-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapSessions', '0002_remove_mapsession_has_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapsession',
            name='sessionInfo',
            field=models.CharField(blank=True),
        ),
    ]
