# Generated by Django 6.0.7 on 2026-08-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapSessions', '0003_mapsession_sessioninfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapsession',
            name='sessionInfo',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
